In [1]:
import pandas as pd
from splinter import Browser
from bs4 import BeautifulSoup
import requests

In [2]:
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [3]:
url= "https://www.worldometers.info/coronavirus/"
browser.visit(url)

In [12]:
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

table = soup.find('table', class_='table table-bordered table-hover main_table_countries dataTable no-footer')

for each in table:
    print(each)

<thead>
<tr role="row"><th aria-label="#" class="sorting_disabled" colspan="1" rowspan="1" style="width: 21px;" width="1%">#</th><th aria-controls="main_table_countries_today" aria-label="Country,Other: activate to sort column ascending" class="sorting" colspan="1" rowspan="1" style="width: 101px;" tabindex="0" width="100">Country,<br/>Other</th><th aria-controls="main_table_countries_today" aria-label="TotalCases: activate to sort column ascending" aria-sort="descending" class="sorting_desc" colspan="1" rowspan="1" style="width: 64px;" tabindex="0" width="20">Total<br/>Cases</th><th aria-controls="main_table_countries_today" aria-label="NewCases: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="width: 44px;" tabindex="0" width="30">New<br/>Cases</th><th aria-controls="main_table_countries_today" aria-label="TotalDeaths: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="width: 47px;" tabindex="0" width="30">Total<br/>Deaths</th><th aria-controls="main_table_countries_today" aria-label="NewDeaths: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="width: 47px;" tabindex="0" width="30">New<br/>Deaths</th><th aria-controls="main_table_countries_today" aria-label="TotalRecovered: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="width: 72px;" tabindex="0" width="30">Total<br/>Recovered</th><th aria-controls="main_table_countries_today" aria-label="ActiveCases: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="width: 56px;" tabindex="0" width="30">Active<br/>Cases</th><th aria-controls="main_table_countries_today" aria-label="Serious,Critical: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="width: 56px;" tabindex="0" width="30">Serious,<br/>Critical</th><th aria-controls="main_table_countries_today" aria-label="Tot&amp;nbsp;Cases/1M pop: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="width: 70px;" tabindex="0" width="30">TotÂ Cases/<br/>1M pop</th><th aria-controls="main_table_countries_today" aria-label="Deaths/1M pop: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="width: 51px;" tabindex="0" width="30">Deaths/<br/>1M pop</th><th aria-controls="main_table_countries_today" aria-label="TotalTests: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="width: 65px;" tabindex="0" width="30">Total<br/>Tests</th><th aria-controls="main_table_countries_today" aria-label="Tests/
1M pop
: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="width: 49px;" tabindex="0" width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th><th aria-controls="main_table_countries_today" aria-label="Population: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="width: 78px;" tabindex="0" width="30">Population</th><th aria-controls="main_table_countries_today" aria-label="Continent: activate to sort column descending" class="sorting" colspan="1" rowspan="1" style="display: none; width: 0px;" tabindex="0" width="30">Continent</th></tr>
</thead>


<tbody>
<tr class="total_row_world odd" role="row">
<td></td>
<td style="text-align:left;">World</td>
<td class="sorting_1">117,263,512</td>
<td>+195,109</td>
<td>2,602,486</td>
<td>+3,232</td>
<td>92,790,233</td>
<td>21,870,793</td>
<td>89,747</td>
<td>15,044</td>
<td>333.9</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
</tr><tr class="total_row_world row_continent even" data-continent="Europe" role="row" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td class="sorting_1">35,088,888</td>
<td>+95,721</td>
<td>834,674</td>
<td>+1,406</td>
<td>24,636,661</td>
<td>9,617,553</td>
<td>26,237</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
</tr><tr class="total_row_world row_continent odd" data-continent="North America" role="row" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td class="sorting_1">34,054,219</td>
<td>+15,036</td>
<td>776,757</td>
<td>+993</td>
<td>23,914,756</td>
<td>9,362,706</td>
<td>19,931</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
</tr><tr class="even" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">29,660,138</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,247</td>
<td style="font-weight: bold; text-align:right;">537,312 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+193</td>
<td style="font-weight: bold; text-align:right">20,274,059</td>
<td style="text-align:right;font-weight:bold;">8,848,767</td>
<td style="font-weight: bold; text-align:right">13,390</td>
<td style="font-weight: bold; text-align:right">89,252</td>
<td style="font-weight: bold; text-align:right">1,617</td>
<td style="font-weight: bold; text-align:right">368,213,824</td>
<td style="font-weight: bold; text-align:right">1,108,009</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">332,320,317</a> </td>
<td data-continent="North America" style="display:none">North America</td>
</tr><tr class="total_row_world row_continent odd" data-continent="Asia" role="row" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td class="sorting_1">25,546,685</td>
<td>+75,307</td>
<td>404,109</td>
<td>+670</td>
<td>23,961,733</td>
<td>1,180,843</td>
<td>22,250</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
</tr><tr class="total_row_world row_continent even" data-continent="South America" role="row" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td class="sorting_1">18,533,275</td>
<td>+5,955</td>
<td>480,092</td>
<td>+87</td>
<td>16,691,701</td>
<td>1,361,482</td>
<td>18,855</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
</tr><tr class="odd" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">11,228,288</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+17,708</td>
<td style="font-weight: bold; text-align:right;">157,875 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+84</td>
<td style="font-weight: bold; text-align:right">10,880,059</td>
<td style="text-align:right;font-weight:bold;">190,354</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">8,083</td>
<td style="font-weight: bold; text-align:right">114</td>
<td style="font-weight: bold; text-align:right">221,430,507</td>
<td style="font-weight: bold; text-align:right">159,395</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,389,197,541</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
</tr><tr class="even" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">10,939,320</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">264,446 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">9,704,351</td>
<td style="text-align:right;font-weight:bold;">970,523</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">51,218</td>
<td style="font-weight: bold; text-align:right">1,238</td>
<td style="font-weight: bold; text-align:right">28,600,000</td>
<td style="font-weight: bold; text-align:right">133,905</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">213,584,556</a> </td>
<td data-continent="South America" style="display:none">South America</td>
</tr><tr class="odd" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">4,322,776</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+10,595</td>
<td style="font-weight: bold; text-align:right;">89,094 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+368</td>
<td style="font-weight: bold; text-align:right">3,911,924</td>
<td style="text-align:right;font-weight:bold;">321,758</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">29,613</td>
<td style="font-weight: bold; text-align:right">610</td>
<td style="font-weight: bold; text-align:right">112,900,000</td>
<td style="font-weight: bold; text-align:right">773,409</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,977,047</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr><tr class="even" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">4,218,520</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+5,177</td>
<td style="font-weight: bold; text-align:right;">124,419 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">3,199,565</td>
<td style="text-align:right;font-weight:bold;">894,536</td>
<td style="font-weight: bold; text-align:right">1,542</td>
<td style="font-weight: bold; text-align:right">61,920</td>
<td style="font-weight: bold; text-align:right">1,826</td>
<td style="font-weight: bold; text-align:right">94,197,029</td>
<td style="font-weight: bold; text-align:right">1,382,644</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,128,167</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr><tr class="total_row_world row_continent odd" data-continent="Africa" role="row" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td class="sorting_1">3,988,079</td>
<td>+3,018</td>
<td>105,746</td>
<td>+76</td>
<td>3,550,351</td>
<td>331,982</td>
<td>2,471</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
</tr><tr class="even" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">3,882,408</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">88,444 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">264,909</td>
<td style="text-align:right;font-weight:bold;">3,529,055</td>
<td style="font-weight: bold; text-align:right">3,689</td>
<td style="font-weight: bold; text-align:right">59,390</td>
<td style="font-weight: bold; text-align:right">1,353</td>
<td style="font-weight: bold; text-align:right">54,630,785</td>
<td style="font-weight: bold; text-align:right">835,694</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,371,726</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr><tr class="odd" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">3,149,012</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">71,138 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">2,744,664</td>
<td style="text-align:right;font-weight:bold;">333,210</td>
<td style="font-weight: bold; text-align:right">2,571</td>
<td style="font-weight: bold; text-align:right">67,334</td>
<td style="font-weight: bold; text-align:right">1,521</td>
<td style="font-weight: bold; text-align:right">39,313,189</td>
<td style="font-weight: bold; text-align:right">840,616</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,767,102</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr><tr class="even" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">3,067,486</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+20,765</td>
<td style="font-weight: bold; text-align:right;">99,785 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+207</td>
<td style="font-weight: bold; text-align:right">2,494,839</td>
<td style="text-align:right;font-weight:bold;">472,862</td>
<td style="font-weight: bold; text-align:right">2,605</td>
<td style="font-weight: bold; text-align:right">50,785</td>
<td style="font-weight: bold; text-align:right">1,652</td>
<td style="font-weight: bold; text-align:right">42,342,845</td>
<td style="font-weight: bold; text-align:right">701,026</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,401,273</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr><tr class="odd" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">2,780,417</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+11,187</td>
<td style="font-weight: bold; text-align:right;">29,030 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+65</td>
<td style="font-weight: bold; text-align:right">2,623,924</td>
<td style="text-align:right;font-weight:bold;">127,463</td>
<td style="font-weight: bold; text-align:right">1,261</td>
<td style="font-weight: bold; text-align:right">32,729</td>
<td style="font-weight: bold; text-align:right">342</td>
<td style="font-weight: bold; text-align:right">34,122,851</td>
<td style="font-weight: bold; text-align:right">401,664</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">84,953,710</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
</tr><tr class="even" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">2,502,872</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+750</td>
<td style="font-weight: bold; text-align:right;">72,473 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+3</td>
<td style="font-weight: bold; text-align:right">2,304,300</td>
<td style="text-align:right;font-weight:bold;">126,099</td>
<td style="font-weight: bold; text-align:right">2,848</td>
<td style="font-weight: bold; text-align:right">29,808</td>
<td style="font-weight: bold; text-align:right">863</td>
<td style="font-weight: bold; text-align:right">45,114,160</td>
<td style="font-weight: bold; text-align:right">537,291</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,966,033</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
</tr><tr class="odd" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">2,273,245</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">60,412 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">2,172,418</td>
<td style="text-align:right;font-weight:bold;">40,415</td>
<td style="font-weight: bold; text-align:right">1,982</td>
<td style="font-weight: bold; text-align:right">44,356</td>
<td style="font-weight: bold; text-align:right">1,179</td>
<td style="font-weight: bold; text-align:right">11,695,919</td>
<td style="font-weight: bold; text-align:right">228,212</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/colombia-population/">51,250,222</a> </td>
<td data-continent="South America" style="display:none">South America</td>
</tr><tr class="even" role="row" style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>
<td class="sorting_1" style="font-weight: bold; text-align:right">2,146,714</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">52,870 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">1,940,317</td>
<td style="text-align:right;font-weight:bold;">153,527</td>
<td style="font-weight: bold; text-align:right">3,475</td>
<td style="font-weight: bold; text-align:right">47,205</td>
<td style="font-weight: bold; text-align:right">1,163</td>
<td style="font-weight: bold; text-align:right">7,697,759</td>
<td style="font-weight: bold; text-align:right">169,268</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/argentina-population/">45,476,874</a> </td>
<td data-continent="South America" style="display:none">South America</td>
</tr><tr class="odd" role="row" style="">